# Generated by Django 6.0.4 on 2026-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_probability',
            field=models.FloatField(),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'country_id', 'age'], name='api_profile_gender_2adee5_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age_group', 'country_id', 'age'], name='api_profile_age_gro_3e0ad5_idx'),
        ),
    ]
