# Generated by Django 6.0.4 on 2026-04-29 04:04

import authentication.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=128, unique=True)),
                ("code_challenge", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("callback_port", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "oauth_states",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=authentication.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("github_id", models.CharField(max_length=50, unique=True)),
                ("username", models.CharField(max_length=150)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "avatar_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("analyst", "Analyst")],
                        default="analyst",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=authentication.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=128, unique=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "db_table": "refresh_tokens",
            },
        ),
    ]
