# Generated by Django 6.0.4 on 2026-04-29 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OAuthState",
        ),
    ]
